<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-03-19 13:44
=======
# Generated by Django 2.0.3 on 2018-03-18 16:39
>>>>>>> 43b234670c5cf7294d586ad85dc5c6fe4cca4ee5

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('img_post', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('img_profile', models.ImageField(blank=True, null=True, upload_to='')),
=======
            name='Its_Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
>>>>>>> 43b234670c5cf7294d586ad85dc5c6fe4cca4ee5
                ('posts', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='its_me.Profile'),
        ),
=======
>>>>>>> 43b234670c5cf7294d586ad85dc5c6fe4cca4ee5
    ]
