# Generated by Django 2.0.3 on 2018-03-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muwahahahahaha', models.CharField(max_length=1337)),
            ],
        ),
    ]
