# Generated by Django 2.0.3 on 2018-03-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_me', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
