# Generated by Django 2.0.3 on 2018-03-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_me', '0003_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
