# Generated by Django 2.0.3 on 2018-03-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_me', '0005_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
