# Generated by Django 2.0.3 on 2018-03-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its_me', '0008_auto_20180321_1015'),
        ('its_me', '0002_auto_20180320_1743'),
    ]

    operations = [
    ]
